services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "3000:3000"
    depends_on:
      - runner
      - mongo
    restart: always

  runner:
    build:
      context: .
      dockerfile: Dockerfile.runner
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  mongo:
    image: mongo:7
    container_name: online-compiler-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data: