FROM docker:27-cli AS dockercli

FROM node:20

WORKDIR /app

# Copy Docker CLI only
COPY --from=dockercli /usr/local/bin/docker /usr/local/bin/docker

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 5000

CMD ["node", "runner.js"]